### PR TITLE
Fix require

### PR DESCRIPTION
**Pull request by gflohr**
A "require" in Ruby code caused a syntax error.  Fixed and test case added.

### CODE REVIEW

**Comment by shlomif** [comment]
Thanks! I'll take a look.

**Comment by shlomif** [comment]
Merged, thanks!

Some notes:

1. `t/cpan-changes.t` was broken - please make sure you have installed all optional dependencies.

2. See http://perl-begin.org/tutorials/bad-elements/#string-notation regarding unquoted here-docs.

**Comment by gflohr** [comment]
Hi,

thanks for merging!

> On Sep 8, 2017, at 12:58, Shlomi Fish <notifications@github.com> wrote:
> 
> Merged, thanks!
> 
> Some notes:
> 
> t/cpan-changes.t was broken - please make sure you have installed all optional dependencies.
> 
> 

I didn’t want to insert a date into Changes.

> 
> See http://perl-begin.org/tutorials/bad-elements/#string-notation <http://perl-begin.org/tutorials/bad-elements/#string-notation> regarding unquoted here-docs.
> 
> 

For Inline::Ruby I will follow and will avoid the naked EOF.  For my own modules not. ;) I personally think, the less interpunction, the better readable.

Things for the future: Being able to call Perl back from Ruby as well would be really nice.  I have seen that there is a compile-time switch but I haven’t tried it out.

IMHO, there should also be an option to never cache the results of compiling the Ruby code.  The positive effect is neglectable for typical use cases, the cache directory is really ugly, and it’s an unnecessary source of subtle bugs.

Cheers,
Guido

**Comment by shlomif** [comment]
Hi Guido,

On Fri, 08 Sep 2017 06:51:52 -0700
Guido Flohr <notifications@github.com> wrote:

> Hi,
> 
> thanks for merging!
> 

yw. Thanks for the commits.

> > On Sep 8, 2017, at 12:58, Shlomi Fish <notifications@github.com> wrote:
> > 
> > Merged, thanks!
> > 
> > Some notes:
> > 
> > t/cpan-changes.t was broken - please make sure you have installed all
> > optional dependencies.
> > 
> >   
> 
> I didn’t want to insert a date into Changes.
> 

Then you should have added "Unknown".

> > 
> > See http://perl-begin.org/tutorials/bad-elements/#string-notation
> > <http://perl-begin.org/tutorials/bad-elements/#string-notation> regarding
> > unquoted here-docs.
> > 
> >   
> 
> For Inline::Ruby I will follow and will avoid the naked EOF.  For my own
> modules not. ;) I personally think, the less interpunction, the better
> readable.

Thanks!

> 
> Things for the future: Being able to call Perl back from Ruby as well would
> be really nice.  I have seen that there is a compile-time switch but I
> haven’t tried it out.
> 

Yes, it will. PRs are welcome.

> IMHO, there should also be an option to never cache the results of compiling
> the Ruby code.  The positive effect is neglectable for typical use cases, the
> cache directory is really ugly, and it’s an unnecessary source of subtle bugs.
> 

Sounds good too.

Regards,

	Shlomi Fish

> Cheers,
> Guido
> 



-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
My Aphorisms - http://www.shlomifish.org/humour.html

 * rindolf demands equal rights for years, minutes, hours and days to also get
   YAAKOV’S GREAT HUGE LOVE.
    —  http://www.shlomifish.org/humour/fortunes/sharp-perl.html

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by gflohr** [comment]
Hi,

> On Sep 8, 2017, at 18:35, Shlomi Fish <notifications@github.com> wrote:
> > I didn’t want to insert a date into Changes.
> > 
> 
> Then you should have added "Unknown”.

I see.  I didn’t know that works.

Cheers,
Guido

**Pull request merged**
